export {default as Home} from './Home/Home'
export {default as Login} from './Login/Login'
export {default as SignUp} from './SignUp/SignUp'
export {default as AboutUs} from './AboutUs/AboutUs'
export {default as Nomatch} from './Nomatch/Nomatch'
